<?php
$active_group = 'default';
$active_record = TRUE;
$db['default']['username'] = 'svnuser';
$db['default']['password'] = 'pXc9nbmrnCnpXhza';
$db['default']['hostname'] = '192.168.1.243';
$db['default']['database'] = 'Taximobility-v1.0.7-oenvbx';
$db['default']['dbdriver'] = 'mysqli';
$db['default']['dbprefix'] = '';
$db['default']['pconnect'] = FALSE;
$db['default']['db_debug'] = FALSE;
$db['default']['cache_on'] = FALSE;
$db['default']['cachedir'] = '';
$db['default']['char_set'] = 'utf8';
$db['default']['dbcollat'] = 'utf8_general_ci';
/* Autogenerated Configuration for db 2016-04-08 */
